### ISSUE TITLE
Error while generating json

### ISSUE THREAD

**Issue by Shad0wGlitch** [tuhinpal/WhatsBot#76]
```
(node:482572) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:14:123
    at ExecutionContext._evaluateInternal (/home/WhatsBot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:482572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:482572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mdestafadilah** [comment]
please run as root
