### ISSUE TITLE
Error Creating While Getting `sesson.secure`

### ISSUE THREAD

**Issue by thealidev** [tuhinpal/WhatsBot#80]
```
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/app/node_modules/whatsapp-web.js/src/Client.js:267:9)
```

**Comment by MoonDusk1996** [comment]
same here

**Comment by sjanaX01** [comment]
You need to fix this.

**Comment by thealidev** [comment]
Hey everyone
Note that this repostry is no longer maintained
Because i think that it's original maintainer ran away
